version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: .env
    environment:
      SIM_API_URL: "http://api:8000/run_sim" # override for in-cluster calls
      FRONTEND_ORIGIN: "http://localhost:3000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: "http://localhost:8000"
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
